# Generated by Django 2.2.7 on 2021-01-04 06:49

import api.models
import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('block', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('reviewe_value', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaysofWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daysofweek', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=564)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('birthday', models.DateField(auto_now=True)),
                ('age', models.IntegerField(default=api.models.DaysofWeek)),
                ('gender', models.CharField(max_length=100)),
                ('testes', models.CharField(max_length=100)),
                ('discription', models.CharField(default='', max_length=1000)),
                ('characterneed', models.IntegerField()),
                ('values', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BloodType', verbose_name=builtins.id)),
                ('dayofbirth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DaysofWeek', verbose_name=builtins.id)),
            ],
        ),
        migrations.CreateModel(
            name='NakSus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naksus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PictureURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picpost', models.TextField(blank=True, default='')),
                ('discription', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesOfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('nope', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', verbose_name=builtins.id)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='naksus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NakSus', verbose_name=builtins.id),
        ),
        migrations.AddField(
            model_name='member',
            name='profileurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PictureURL', verbose_name=builtins.id),
        ),
        migrations.AddField(
            model_name='member',
            name='rasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RaSi', verbose_name=builtins.id),
        ),
        migrations.CreateModel(
            name='Goldmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Conversation', verbose_name=builtins.id)),
                ('goldmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', verbose_name=builtins.id)),
                ('values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ValuesOfall', verbose_name=builtins.id)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', verbose_name=builtins.id),
        ),
    ]
