# Generated by Django 2.2.7 on 2021-02-12 16:50

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='imageprofile',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='api.Image'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='imageprofile2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/', verbose_name='ImageProflie'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='personality',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='api.Personality'),
        ),
    ]
