# Generated by Django 2.2.7 on 2020-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='friday',
            field=models.CharField(default='Friday', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='monday',
            field=models.CharField(default='Monday', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='saturday',
            field=models.CharField(default='Saturday', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='sunday',
            field=models.CharField(default='Sunday', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='thursday',
            field=models.CharField(default='Thursday', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='tuesday',
            field=models.CharField(default='Tuesday', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='wednesday',
            field=models.CharField(default='Wednesday', max_length=25),
        ),
    ]
