# Generated by Django 2.2.7 on 2021-02-05 16:59

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='imageprofile2',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='ImageProflie'),
        ),
    ]
