# Generated by Django 2.2.7 on 2021-02-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_conversation_memberprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldmember',
            name='user',
        ),
    ]
