# Generated by Django 2.2.7 on 2021-02-13 01:43

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_goldmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='imagenetwork',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
