# Generated by Django 2.2.7 on 2021-02-13 01:56

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210213_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
