# Generated by Django 2.2.7 on 2021-02-13 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210213_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='noped',
            field=models.ManyToManyField(blank=True, null=True, related_name='noped', to=settings.AUTH_USER_MODEL),
        ),
    ]
