# Generated by Django 2.2.7 on 2021-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ratingPoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
