# Generated by Django 2.2.7 on 2021-04-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
