# Generated by Django 2.2.7 on 2021-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='testes',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1, null=True),
        ),
    ]
