# Generated by Django 2.2.7 on 2021-03-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nope',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
