# Generated by Django 2.2.7 on 2021-03-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210315_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreOfRaSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('memberA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasi_pk_req', to='members.Profile')),
                ('memberB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasi_pk_all', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOfNakSus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('memberA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naksus_pk_req', to='members.Profile')),
                ('memberB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naksus_pk_all', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOfDaysOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('memberA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daysofweek_pk_req', to='members.Profile')),
                ('memberB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daysofweek_pk_all', to='members.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOfBloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('memberA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodType_pk_req', to='members.Profile')),
                ('memberB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodType_pk_all', to='members.Profile')),
            ],
        ),
    ]
