# Generated by Django 2.2.7 on 2021-04-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_match_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='daysofweek',
            options={},
        ),
        migrations.AlterModelOptions(
            name='naksus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rasi',
            options={},
        ),
    ]
