# Generated by Django 2.2.7 on 2021-03-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210315_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreofbloodtype',
            name='memberA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_item', to='members.BloodType'),
        ),
        migrations.AlterField(
            model_name='scoreofbloodtype',
            name='memberB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_item', to='members.BloodType'),
        ),
    ]
