# Generated by Django 3.1.4 on 2020-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('birth', models.DateField(auto_now=True)),
                ('discription', models.CharField(default='', max_length=1000)),
                ('sexual', models.CharField(max_length=100)),
                ('sextest', models.CharField(max_length=100)),
                ('link_pic', models.TextField(blank=True, default='')),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
