# Generated by Django 3.1.4 on 2020-12-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taffy', '0002_auto_20201216_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='member',
            name='link_pic',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sextest',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sexual',
        ),
    ]
