# Generated by Django 2.2.7 on 2021-05-06 16:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210505_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
