# Generated by Django 2.2.7 on 2020-12-28 15:42

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=api.models.DayOfBirth)),
                ('birthday', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfBirth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofbirth', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filttertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=564)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('profileurl', models.TextField(blank=True, default='')),
                ('discription', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='NakSus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naksus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RaSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SexTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sextest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexual', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PictureURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picurl', models.TextField(blank=True, default='')),
                ('discription', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Conversation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='NopeOfALl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nopeUall', models.BooleanField(default=True)),
                ('deductscroce', models.IntegerField(verbose_name=-10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, default='')),
                ('time_at', models.DateTimeField(auto_now_add=True)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='sexaul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sexual'),
        ),
        migrations.AddField(
            model_name='member',
            name='sextest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SexTest'),
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Birthday')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='LikeOfAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeUall', models.BooleanField(default=True)),
                ('addscroce', models.IntegerField(verbose_name=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='LikeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Goldmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goldmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
                ('likeUall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LikeOfAll')),
            ],
        ),
        migrations.CreateModel(
            name='FilteredBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Birthday')),
                ('filtertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FilterType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='newmember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='bloodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BloodType'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='dayofbirth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DayOfBirth'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='naksus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NakSus'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='rasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RaSi'),
        ),
    ]
